### ISSUE TITLE
Can you point out the differences between wildfire.vim and vim-expand-region?

### ISSUE THREAD

**Issue by pgilad** [gcmt/wildfire.vim#8]
Just wondering what the differences are, it would probably be a best solution to join forces if they are the same, no?

I'm not representing anyone, just coming from someone who wonders what package to use.

vim-expand-region:
https://github.com/terryma/vim-expand-region

If there are differences, I think it's important to highlight them so that users who (like me) are considering which package to use can decide.

**Comment by ches** [comment]
This capability may have been added since this thread, but one advantage for Wildfire is that you can simultaneously use multiple sets of text objects in one filetype with different mappings—as far I can tell so far, with vim-expand-region you're limited to a global dictionary and one global dict per-filetype. In a Lisp-y language (which is probably where these plugins are most valuable), it might be really handy to have two mappings, one that includes "inside" text objects, and the other with "around" mappings.

VER might have an API to allow this, but it's not documented.
